Completando documetação da classe Sorteio.
kyriosdata/mega-sena pull request #35
Opened 2019-05-31 00:48 UTC by rebeccamoraes

1. Caracteres "estranhos" foram substituídos por correspondente correto em UTF-8. 
2. Documentação dos métodos da classe feitos.

2019-05-31 16:53 UTC, kyriosdata requested changes
Veja as considerações feitas.

2019-05-31 16:53 UTC, kyriosdata commented on src/main/java/megasena/Sorteio.java
> +     * Obtem o valor do Sorteio em formato de texto.
Verifica demais usos Obtém em vez de Obtem (sem acento).

2019-05-31 16:53 UTC, kyriosdata commented on src/main/java/megasena/Sorteio.java
> +     * Obtem o valor de valorAcumulado.
Ambos os métodos get/set para valorAcumulado precisam de ajustes na documentação. Talvez melhor seja "definir/obter o valor acumulado". Observe que uma classe deve "fazer sentido" para o seu usuário e, neste caso, simplesmente definir ou obter o valor de uma variável, não fornece nenhum encapsulamento esperado de uma classe.

2019-06-03 02:54 UTC, rebeccamoraes commented on src/main/java/megasena/Sorteio.java
> +     * Obtem o valor do Sorteio em formato de texto.
Resolvido 613ee886c4ad405d590421ff49d10aebeff99ac7

2019-06-03 18:54 UTC, kyriosdata approved these changes

2019-06-03 18:54 UTC, merged